# Revenue Prediction
Tujuan: Memprediksi revenue pelanggan.

## 1. Data Loading
Tujuan: Menampilkan dan melihat gambaran besar data.

In [2]:
import pandas as pd

df = pd.read_csv("../data/processed/telco_clean.csv")
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,...,MonthlyCharges,TotalCharges,Churn,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,InternetService_No,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,0,1,0,1,0,0,1,0,0,...,29.85,29.85,0,1,0,0,0,0,1,0
1,1,0,0,0,34,1,1,0,1,0,...,56.95,1889.50,0,0,0,0,0,0,0,1
2,1,0,0,0,2,1,1,1,0,0,...,53.85,108.15,1,0,0,0,0,0,0,1
3,1,0,0,0,45,0,1,0,1,1,...,42.30,1840.75,0,1,0,0,0,0,0,0
4,0,0,0,0,2,1,0,0,0,0,...,70.70,151.65,1,0,0,1,0,0,1,0


## 2. Tentukan Target
Tujuan: Menentukan dan memisahkan target.

In [3]:
X = df.drop("TotalCharges", axis=1)

y = df["TotalCharges"]

# catatan : Churn bisa menjadi informasi yang berguna, sehingga tidak kita drop.

## 3. Data Splitting
Tujuan: Memisahkan dan membagi data.

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

## 4. Scaling
Tujuan: Mengubah nilai dari berbagai fitur (variabel) dalam dataset agar memiliki rentang skala yang seragam.

In [5]:
num_cols = [
    "tenure",
    "MonthlyCharges"
]

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train[num_cols] = scaler.fit_transform(
    X_train[num_cols]
)

X_test[num_cols] = scaler.transform(
    X_test[num_cols]
)

In [6]:
import joblib


joblib.dump(
    scaler,
    "../models/scaler_revenue.pkl"
)

['../models/scaler_revenue.pkl']

## 5. Model Regresi
Tujuan: Mencoba dan menggunakan banyak model untuk menemukan yang terbaik.

In [7]:
# Linear Regression
from sklearn.linear_model import LinearRegression

# Polynomial Regression
from sklearn.preprocessing import PolynomialFeatures

# Decision Tree Regressor
from sklearn.tree import DecisionTreeRegressor

# SVR
from sklearn.svm import SVR

# Neural Network
from sklearn.neural_network import MLPRegressor


models = {
    "Linear Regression":
        LinearRegression(),

    # Polynomial Regression terpisah
    
    "Decision Tree":
        DecisionTreeRegressor(
            random_state=42
        ),

    "SVR":
        SVR(),

    "Neural Network":
        MLPRegressor(
            random_state=42,
            max_iter=1000
        )
}

In [8]:
poly = PolynomialFeatures(
    degree=2
)

X_train_poly = poly.fit_transform(
    X_train
)

X_test_poly = poly.transform(
    X_test
)

In [9]:
poly_model = LinearRegression()

poly_model.fit(
    X_train_poly,
    y_train
)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [10]:
y_pred_poly = poly_model.predict(
    X_test_poly
)

## 6. Evaluasi
Tujuan: Menemukan model terbaik.

In [11]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

results = []

# evaluasi model

for name, model in models.items():

    model.fit(
        X_train,
        y_train
    )

    y_pred = model.predict(
        X_test
    )

    mae = mean_absolute_error(
        y_test,
        y_pred
    )

    mse = mean_squared_error(
        y_test,
        y_pred
    )

    rmse = mse ** 0.5

    r2 = r2_score(
        y_test,
        y_pred
    )

    results.append([
        name,
        mae,
        mse,
        rmse,
        r2
    ])


C:\Users\Asus\AppData\Roaming\Python\Python314\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


In [12]:
# evaluasi polynomial
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

mae = mean_absolute_error(
    y_test,
    y_pred_poly
)

mse = mean_squared_error(
    y_test,
    y_pred_poly
)

rmse = mse ** 0.5

r2 = r2_score(
    y_test,
    y_pred_poly
)

results.append([
    "Polynomial Regression",
    mae,
    mse,
    rmse,
    r2
])

In [13]:
# tampilkan

results_df = pd.DataFrame(
    results,
    columns=[
        "Model",
        "MAE",
        "MSE",
        "RMSE",
        "R2"
    ]
)

results_df.sort_values(
    by="R2",
    ascending=False
)

,Model,MAE,MSE,RMSE,R2
4,Polynomial Regression,49.151408,5.073310e+03,71.227174,0.999018
3,Neural Network,53.250610,5.904468e+03,76.840535,0.998857
1,Decision Tree,82.603554,1.511974e+04,122.962356,0.997074
0,Linear Regression,539.714333,4.536135e+05,673.508378,0.912219
2,SVR,1453.585588,4.374625e+06,2091.560412,0.153444


Insight :

1. Model Terbaik: Polynomial Regression (Peringkat 4)
* **Akurasi Tertinggi**: Memiliki nilai **R2 sebesar 0.999018**, yang berarti model mampu menjelaskan sekitar 99.9% varians data target.
* **Error Terendah**: Mencatat nilai error paling minimum di antara semua model:
  * **MAE**: 49.15
  * **RMSE**: 71.22
* **Rekomendasi**: Model ini adalah pilihan utama untuk digunakan dalam produksi karena performanya yang paling optimal dan presisinya yang tinggi.

2. Model Kompetitor Terdekat: Neural Network (Peringkat 3)
* Menempati posisi kedua dengan performa yang sangat mendekati model terbaik (**R2: 0.998857**).
* Nilai error sedikit lebih tinggi dari Polynomial Regression (MAE: 53.25, RMSE: 76.84). 
* Dapat dijadikan model alternatif jika karakteristik data dasar mengalami perubahan struktural di masa depan.

3. Model Performa Menengah: Decision Tree & Linear Regression (Peringkat 1 & 0)
* **Decision Tree** memberikan hasil yang cukup baik (**R2: 0.997074**), namun memiliki lompatan error (*variance*) yang lebih tinggi dibanding dua model teratas.
* **Linear Regression** menunjukkan keterbatasan dalam menangkap pola data (**R2: 0.912219**) dengan tingkat error yang mulai membengkak signifikan (RMSE: 673.51). Hal ini mengindikasikan bahwa hubungan antar variabel dalam data cenderung bersifat non-linear.

4. Model Terburuk: SVR / Support Vector Regression (Peringkat 2)
* **Performa Sangat Rendah**: Nilai **R2 hanya 0.153444**, mengindikasikan model gagal mempelajari pola data dengan baik.
* **Error Ekstrem**: Memiliki tingkat kesalahan yang sangat masif (MAE: 1453.58, RMSE: 2091.56). Model ini harus dieliminasi atau memerlukan penyetelan parameter (*hyperparameter tuning*) yang sangat agresif jika ingin digunakan kembali.



Lima algoritma regresi diuji untuk memprediksi TotalCharges pelanggan. Berdasarkan nilai R² tertinggi (0.9990) dan RMSE terendah (71.23), Polynomial Regression menjadi model terbaik. Hasil ini menunjukkan bahwa hubungan antara fitur pelanggan dan revenue bersifat non-linear, sehingga model yang mampu menangkap interaksi antar fitur memberikan performa yang jauh lebih baik dibanding Linear Regression standar.

Revenue pelanggan sangat dapat diprediksi. Model terbaik berhasil mencapai R² ≈ 99.9% yang menunjukkan bahwa informasi pelanggan yang tersedia telah mampu menjelaskan hampir seluruh variasi pendapatan pelanggan.

In [14]:
joblib.dump(
    poly,
    "../models/polynomial_transformer.pkl"
)

joblib.dump(
    poly_model,
    "../models/revenue_model.pkl"
)

['../models/revenue_model.pkl']